### ISSUE TITLE
Feature Request - Digits "width" & Save an operations list

### ISSUE THREAD

**Issue by Tibimac** [namagicapp/support#1]
Bonjour,

Je viens d'acheter Namagic et je viens de l'utiliser pour la 1ère fois.
Et même si l'application fonctionne tout à fait bien je viens de penser à 2 idées d'améliorations : 
- 1 : Dans l'opération "Add digits sequence" il serait super de pourvoir sélectionner une "largeur" de nombre. Ainsi si je choisis "Start index" à 1 et que je demande une largeur de 3, les nombres créés seront : 001, 002, 003 ..., 010, 011... 100, 101, 102 etc..En fait lors de la création des NSString finale, il faudrait dans la boucle transformer le nombre en texte (avant même qu'il soit inclus dans la NSString finale) puis récupérer la longueur en caractères enfin, si la longueur est inférieure à la largeur de nombre souhaitée, modifier la NSString pour ajouter autant de 0 que nécessaire devant le chiffre.
  ("nbZeroToAdd = (numberWidth - nbCharNumber)"). 
  
  ```
  int numberWidth = 3; // Largeur de nombre
  int number = 2; // Nombre actuel (en vrai nous serions dans une boucle)
  
  NSMutableString *numberString = [NSMutableString stringWithFormat:@"%d", number];
  NSInteger nbZeroToAdd = (numberWidth - [numberString length]);
  
  if (nbZeroToAdd > 0)
  {
      for (int i = 0; i < nbZeroToAdd; i++)
      {
          [numberString setString:[NSString stringWithFormat:@"0%@", numberString]];
      }
  }
  ```

L'utilisateur peut très bien choisir une largeur de 2, en ayant pour autant plus de 99 fichiers à renommer. Ainsi la valeur de nbZeroToAdd sera une valeur négative (donc stocké dans un NSInteger et non pas un NSUInteger pour éviter une execution sans fin à cause du if). Et le if permet d'éviter d'arriver sur le for de manière totalement inutile.

À la sortie du for numberString vaut "002".
- 2 : Deuxième point : il est bien de pouvoir enregistrer une suite d'opérations avec un nom, de manière à pouvoir la réutiliser régulièrement sans avoir à refaire à chaque fois l'enchainement des opérations.

Voilà Johan j'espère que mes idées te semblerons bonnes et que tu les ajouteras. N'hésites pas à me répondre si tu le souhaites.

Bonne journée 😊

**Comment by johansatge** [comment]
Bonjour,

merci pour ce retour !

Le point 1 peut intéresser les utilisateurs je pense, il sera ajouté sous peu.

La feature évoquée dans le second point fait déjà partie de la roadmap, elle devrait être développée d'ici la prochaine version majeure :)

Bonne soirée

**Comment by Tibimac** [comment]
Ok super alors. Merci de ta réponse.
Bonne soirée !

**Comment by johansatge** [comment]
This issue was moved to johansatge/namagic#8
